name: tradeapp
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  dartz: ^0.8.9
  k_chart: ^0.1.1
  http: ^0.12.0+4
  webfeed: ^0.4.2
  url_launcher: ^5.4.2
  cached_network_image: ^2.0.0
 








  
  cupertino_icons: ^0.1.2

dev_dependencies:
  pedantic_mono: any
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  fonts:
  - family:  Tredeapp
    fonts:
      - asset: fonts/Tredeapp.ttf
